name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Tự động triển khai khi có commit lên nhánh main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'  # Đặt phiên bản Python phù hợp

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Heroku CLI
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login heroku" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc

      - name: Set Heroku remote
        run: |
          git remote add heroku https://git.heroku.com/nhan-dien-dai-bieu.git

      - name: Deploy to Heroku
        run: |
          git push heroku main --force  # Ghi đè các thay đổi trên Heroku nếu cần thiết
